# Generated by Django 3.2 on 2021-04-17 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210415_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='money',
            field=models.FloatField(default=1000000),
        ),
    ]
