# Generated by Django 3.2 on 2021-04-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_myuser_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='compay',
            field=models.JSONField(default=34),
            preserve_default=False,
        ),
    ]
