# Generated by Django 3.2 on 2021-04-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_myuser_compay'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='company_list',
            field=models.JSONField(default={'AAPL': 'Apple Inc', 'PFE': 'Pfizer Inc', 'TSLA': 'Tesla Inc'}),
        ),
    ]
