# Generated by Django 3.1.7 on 2021-03-21 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_edit',
            old_name='user_id',
            new_name='user',
        ),
    ]
