# Generated by Django 3.1.7 on 2021-03-21 21:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('after_login', '0002_auto_20210321_2330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_edit',
            new_name='UserEdit',
        ),
    ]
