# Generated by Django 3.1.7 on 2021-04-07 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0004_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('B', 'Purchase'), ('S', 'Sold')], max_length=8),
        ),
    ]
