# Generated by Django 3.1.7 on 2021-04-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0005_auto_20210407_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='company',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(choices=[('Purchased', 'Buy'), ('Sale', 'Sell')], max_length=12),
        ),
    ]
