# Generated by Django 3.1.7 on 2021-04-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0006_auto_20210407_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='plm',
            field=models.CharField(default='dsddd', max_length=34),
            preserve_default=False,
        ),
    ]
