# Generated by Django 3.1.7 on 2021-04-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0009_auto_20210412_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='invested',
            field=models.BigIntegerField(default=123456),
            preserve_default=False,
        ),
    ]
