# Generated by Django 3.1.7 on 2021-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0010_transactions_invested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='invested',
            field=models.FloatField(),
        ),
    ]
