# Generated by Django 3.2 on 2021-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0013_alter_transactions_actual_invested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='actual_invested',
            field=models.FloatField(default=models.FloatField()),
        ),
    ]
