# Generated by Django 3.2 on 2021-04-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0015_alter_transactions_actual_invested'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='profit',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
