# Generated by Django 3.1.7 on 2021-06-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('after_login', '0017_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredit',
            name='model_pic',
            field=models.ImageField(blank=True, default='empty_profile.png', null=True, upload_to=''),
        ),
    ]
